on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string
        default: '[]'

jobs:
  echo_input:
    runs-on: ubuntu-latest
    steps:
      - name: Echo input
        run: |
          if [ "${{toJson(fromJson(inputs.matrix.directory))}}" != '[]' ]; then
            echo "Input matrix Available"
            echo "${{toJson(fromJson(inputs.matrix.directory))}}"
          else
            echo "No input matrix"
          fi

  echo_changed_folders:
    runs-on: ubuntu-latest
    if: ${{fromJson(inputs.matrix).directory}} != '[]'
    strategy:
      matrix: ${{fromJson(inputs.matrix)}}
    steps:
      - name: Checkout code
        run : |
          echo"Checking out code"

      - name: Echo changed directories
        run: |
          echo "${{ matrix.directory }}"