on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string
        default: '[]'

jobs:
  echo_changed_folders:
    runs-on: ubuntu-latest
    if: ${{fromJson(inputs.matrix).directory}} != '[]'
    strategy:
      matrix: ${{fromJson(inputs.matrix)}}
    steps:
      - name: Checkout code
        run : |
          echo"Checking out code"

      - name: Echo changed directories
        run: |
          echo "${{ matrix.directory }}"