on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string
        default: '[]'

jobs:
  echo_changed_folders:
    runs-on: ubuntu-latest
    if: contains(inputs.matrix, '[]') == false
    strategy:
      matrix:
        directory: ${{fromJson(inputs.matrix).directory}}
    steps:
      - name: Echo changed directories
        run: |
          echo "Changed directories: ${{matrix.directory}}"