name: Deploy on Tag

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - prod

permissions:
  id-token: write
  contents: write
  pull-requests: write
  repository-projects: read
  packages: read
  pages: write
  checks: write
  actions: read

env:
  AWS_REGION: 'us-east-1'

jobs:
  plan:
    name: Deploy Plan
    runs-on: ubuntu-latest

    steps:
      - name: Set environment vars
        shell: bash
        run: |
          if [[ ${{inputs.environment}} == 'prod' ]]; then
              echo "AWS_ROLE=arn:aws:iam::949263681218:role/milan-terraform-github-action-write-role" >> $GITHUB_ENV
              echo "ENV=prod" >> $GITHUB_ENV
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.1
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          role-duration-seconds: 3600
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      
      - name: Add github safe dir
        run: git config --global --add safe.directory /__w/terraform-gitops/terraform-gitops

      - name: Init
        id: init
        run: |
          cd environments/${{inputs.environment}}
          terraform init

      - name: Apply
        if: ${{steps.init.outcome}} == 'success'
        id: apply
        run: |
          cd environments/${{inputs.environment}}
          terraform apply --auto-approve